import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";
const outDir="outputs/2026-09-22", outPath=`${outDir}/Учёт часов СПО на 22.09.2026.xlsx`;
const {records,plans}=JSON.parse(await fs.readFile("analysis.json","utf8"));
const starts=["02.09.2026","07.09.2026","14.09.2026","21.09.2026"], wi=d=>d<="2026-09-05"?0:d<="2026-09-12"?1:d<="2026-09-19"?2:3;
const hours=new Map(), weeks=new Map(), detail=new Map();
for(const r of records){hours.set(r.teacher,(hours.get(r.teacher)||0)+2);let w=weeks.get(r.teacher)||[0,0,0,0];w[wi(r.date)]+=2;weeks.set(r.teacher,w);let k=[r.teacher,r.group,r.subject].join("\u0001"),x=detail.get(k)||{...r,hours:0,first:r.date,last:r.date};x.hours+=2;x.first=x.first<r.date?x.first:r.date;x.last=x.last>r.date?x.last:r.date;detail.set(k,x)}
const teachers=Object.keys(plans).sort((a,b)=>a.localeCompare(b,"ru")), wb=Workbook.create();
const summary=wb.worksheets.add("пр"), status=wb.worksheets.add("Статус на 22.09"), groups=wb.worksheets.add("По группам на 22.09"), sources=wb.worksheets.add("Расписание");
function design(s,title,header,body){s.showGridLines=false;s.getRange(title).format={font:{name:"Arial",size:14,bold:true,color:"#1F1F1F"},verticalAlignment:"center"};s.getRange(header).format={fill:"#1F4E78",font:{name:"Arial",size:10,bold:true,color:"#FFFFFF"},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true};s.getRange(body).format.font={name:"Arial",size:10};s.getRange(body).format.borders={preset:"outside",style:"thin",color:"#D9E2F3"};s.freezePanes.freezeRows(2)}
summary.mergeCells("A1:M1");summary.getRange("A1").values=[["Учёт часов преподавателей СПО на 22.09.2026"]];summary.getRange("A2:M2").values=[["Преподаватель","Нагрузка по примеру","Выдано","Остаток","Выполнение","Ср. за неделю",...starts,"Статус","Групп","Занятий"]];
const rows=teachers.map(t=>{let p=plans[t]||0,h=hours.get(t)||0,pct=p?h/p:0,st=pct>=1?"Завершил":pct>=.8?"Близок к завершению":"В процессе",gc=new Set(records.filter(r=>r.teacher===t).map(r=>r.group)).size;return[t,p,h,p-h,pct,h/4,...(weeks.get(t)||[0,0,0,0]),st,gc,h/2]});summary.getRange(`A3:M${rows.length+2}`).values=rows;design(summary,"A1:M1","A2:M2",`A2:M${rows.length+2}`);summary.getRange(`B3:D${rows.length+2}`).format.numberFormat="0";summary.getRange(`E3:E${rows.length+2}`).format.numberFormat="0.0%";summary.getRange(`F3:J${rows.length+2}`).format.numberFormat="0";summary.getRange("A:A").format.columnWidth=35;summary.getRange("B:D").format.columnWidth=17;summary.getRange("E:F").format.columnWidth=15;summary.getRange("G:J").format.columnWidth=13;summary.getRange("K:K").format.columnWidth=24;summary.getRange("L:M").format.columnWidth=11;summary.getRange(`K3:K${rows.length+2}`).conditionalFormats.add("containsText",{text:"Завершил",format:{fill:"#C6E0B4",font:{bold:true,color:"#006100"}}});summary.getRange(`K3:K${rows.length+2}`).conditionalFormats.add("containsText",{text:"Близок",format:{fill:"#FFE699",font:{bold:true,color:"#9C5700"}}});
status.mergeCells("A1:F1");status.getRange("A1").values=[["Преподаватели, завершившие или близкие к завершению"]];status.getRange("A2:F2").values=[["Преподаватель","План из примера","Выдано","Остаток","% выполнения","Статус"]];let sr=rows.filter(r=>r[4]>=.8).map(r=>[r[0],r[1],r[2],r[3],r[4],r[10]]);if(!sr.length)sr=[["Нет преподавателей с выполнением от 80%",null,null,null,null,null]];status.getRange(`A3:F${sr.length+2}`).values=sr;design(status,"A1:F1","A2:F2",`A2:F${sr.length+2}`);status.getRange(`B3:D${sr.length+2}`).format.numberFormat="0";status.getRange(`E3:E${sr.length+2}`).format.numberFormat="0.0%";status.getRange("A:A").format.columnWidth=36;status.getRange("B:E").format.columnWidth=16;status.getRange("F:F").format.columnWidth=24;
groups.mergeCells("A1:G1");groups.getRange("A1").values=[["Учёт выданных часов по преподавателям и группам на 22.09.2026"]];groups.getRange("A2:G2").values=[["Преподаватель","Группа","Дисциплина","Часов","Первое занятие","Последнее занятие","Курс"]];let gr=[...detail.values()].sort((a,b)=>a.teacher.localeCompare(b.teacher,"ru")||a.group.localeCompare(b.group,"ru")).map(x=>[x.teacher,x.group,x.subject,x.hours,x.first,x.last,x.course]);groups.getRange(`A3:G${gr.length+2}`).values=gr;design(groups,"A1:G1","A2:G2",`A2:G${gr.length+2}`);groups.getRange(`D3:D${gr.length+2}`).format.numberFormat="0";groups.getRange("A:A").format.columnWidth=35;groups.getRange("B:B").format.columnWidth=18;groups.getRange("C:C").format.columnWidth=58;groups.getRange("D:D").format.columnWidth=10;groups.getRange("E:F").format.columnWidth=15;groups.getRange("G:G").format.columnWidth=12;
sources.mergeCells("A1:D1");sources.getRange("A1").values=[["Источники расписаний"]];sources.getRange("A2:D2").values=[["Период","Расписание","Учтено до","Правило расчёта"]];sources.getRange("A3:D6").values=[["02–05.09.2026","https://docs.google.com/spreadsheets/d/1I_7Pv07cp2A829x_Rw5aJ3rA6SM-3ICaLOLAFTUXxAM/edit","22.09.2026","2 часа за занятие"],["07–12.09.2026","https://docs.google.com/spreadsheets/d/1gHRTdbbjte1tqb4AFm91AQiHig3wO1HDoMevYXNvlX8/edit","22.09.2026","2 часа за занятие"],["14–19.09.2026","https://docs.google.com/spreadsheets/d/1vlRcwNR0gbhoNCmBEfp-5cIv3U9dxRtxXAP1n53v-to/edit","22.09.2026","2 часа за занятие"],["21–22.09.2026","https://docs.google.com/spreadsheets/d/1MikCATSfxd4IWwvfUOJb9Cp5Gxxu98Vnlt9IXOYb7_o/edit","22.09.2026","2 часа за занятие"]];design(sources,"A1:D1","A2:D2","A2:D6");sources.getRange("A:A").format.columnWidth=18;sources.getRange("B:B").format.columnWidth=70;sources.getRange("C:D").format.columnWidth=20;
wb.recalculate();console.log((await wb.inspect({kind:"table",range:"пр!A1:M15",include:"values,formulas",tableMaxRows:15,tableMaxCols:13})).ndjson);console.log((await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:30},summary:"final formula error scan"})).ndjson);await fs.mkdir(outDir,{recursive:true});let preview=await wb.render({sheetName:"пр",range:"A1:M20",scale:1.2});await fs.writeFile(`${outDir}/summary-preview.png`,new Uint8Array(await preview.arrayBuffer()));let out=await SpreadsheetFile.exportXlsx(wb);await out.save(outPath);
